### ISSUE TITLE
i18n: Feedback text isn't in the chosen language for some sections

### ISSUE THREAD

**Issue by mhvezina** [ualbertalib/DMPonline_v4#38]
"Plan details" and "Data Management Questions" tabs/sections : It seems the feedback text provided to the user (in the yellowish box) isn't in the language chosen by the user. Here are two examples with images: 1) feedback after editing plan details; 2) feedback after adding a comment (same thing for "Comment has been removed"....)
![dmpbuilder_feedbackinfo_whencommentingonequestion](https://cloud.githubusercontent.com/assets/10760472/9449303/b6b5a28c-4a6f-11e5-92ff-5674b9cefd72.png)
![dmpbuilder_feedbackinfo_wheneditingplandetails](https://cloud.githubusercontent.com/assets/10760472/9449305/b6b5db80-4a6f-11e5-85b6-1fd322a97ae9.png)

However Feedbak messages in the "Share" tab/section are ok.

![dmpbuilder_feedbackinfo_ok_whensharingplan](https://cloud.githubusercontent.com/assets/10760472/9449304/b6b5c316-4a6f-11e5-8e7e-8c7c44a1c924.png)

**Comment by weiweishi** [comment]
fixed with 19765bd1c70c217f56aac80f118b026ef739ae4c

**Comment by mhvezina** [comment]
Weiwei,

I just re-tested this and the problem is still there: feedback text "Project was successfully updated" when updating info in the "Plan details" section, is displayed when using the French interface.

Feedback text related to creating/updating comments is in the right language though.

**Comment by weiweishi** [comment]
@mhvezina, could you please send me the translation for the following text:
 Project was successfully updated.
 Comment has been removed.

thanks

**Comment by mhvezina** [comment]
Project was successfully updated. : Le projet a bien été mis à jour.
Comment has been removed. : Le commentaire a été supprimé.

**Comment by mhvezina** [comment]
@weiweishi 
I understand the French translations were provided and everything is fixed; I'm closing this issue.
